[package]
name = "energy_manager"
version = "0.1.0"
authors = ["Daniel Pape <code@75ohm.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "energy_manager"
path = "src/main.rs"
